name: Build Status

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
      - run: npm ci
      - run: npm update
      # Remove the node_modules and re-install with updated package-lock.json
      # because npm update command breaks some of the npm-cli packages
      - run: rm -rf node_modules
      - run: npm ci
      - run: npm test
        env:
          CI: true
